[package]
name = "hive-sense-fw"
version = "1.1.0"
authors = ["Pierrick Curt <pierrickcurt@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-backtrace = { version = "0.13.0", features = [
    "esp32s3",
    "panic-handler",
    "println",
] }

esp-hal = { version = "0.19.0", features = ["async", "esp32s3", "embedded-hal-02"] }
esp-println = { version = "0.10.0", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }

lora-phy = { git = "https://github.com/lora-rs/lora-rs.git", rev="b4b6741152b0bc599574eecff9a7ffc031ba1823", features = ["lorawan-radio"]}
lorawan-device = { git = "https://github.com/lora-rs/lora-rs.git", rev="b4b6741152b0bc599574eecff9a7ffc031ba1823", default-features = false, features = ["embassy-time", "default-crypto"]}
embassy-executor =  { version = "0.5.0" }
embassy-time =  { version = "0.3.0" }
embedded-hal-bus = { version = "0.1.0", features = ["async"] }
loadcell = "0.2.0"
esp-hal-embassy = { version = "0.2.0", features = ["esp32s3", "integrated-timers"] }
esp-wifi = { version = "0.7.1", features = [
    "esp32s3",
    "wifi-default",
    "utils",
    "phy-enable-usb",
] }
heapless = { version = "0.8.0", default-features = false }
embedded-cli = "0.2.1"
embedded-io = "0.6.1"
ufmt = "0.2.0"
esp-storage = { version = "0.3.0", features = ["esp32s3"] }
embedded-storage = "0.3.1"
embassy-sync = "0.6.0"
static_cell = { version = "2.1.0", features = ["nightly"] }

[profile.dev]
# Rust debug is too slow. 
# For debug builds always builds with some optimization
opt-level = "s"

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false

