name: Release hive-sense-fw

on:
  push:
    tags:        
      - v*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - name: Install libudev-dev   
        run: sudo apt-get install libudev-dev
      - name: Install esp tools
        run: cargo install espflash
      - name: Build
        run: cargo build --release
      - name: Create bin
        run: espflash save-image --chip esp32s3 target/xtensa-esp32s3-none-elf/release/hive-sense-fw hive-sense-fw.bin
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: hive-sense-fw.bin
